[package]

name = "ecs"
version = "0.7.1"
authors = [
    "HeroesGrave <heroesgrave@gmail.com>",
    "Tom Bebbington <tophattedcoder@gmail.com>",
    "Jake Kerr <kodafox@gmail.com>",
]

[dependencies.uuid]

git = "https://github.com/rust-lang/uuid"
